on: push
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    TARGET_PATHS: README.MD,iOSResourcesList.md
    steps:
      - uses: technote-space/toc-generator@v4.3.1
            
